### ISSUE TITLE
Cool Stuffs!

### ISSUE THREAD

**Issue by Godly-Avenger** [13-05/waves#1]
- [x] [yt-dlp](https://github.com/yt-dlp/yt-dlp)
- [x] [Catpuccin](https://github.com/catppuccin)
- [x] [DALL-E Mini](https://github.com/borisdayma/dalle-mini)
- [x] [Saved for Reddit](https://github.com/pvik/saved-for-reddit)
- [x] [Discord Mass Report Bot](https://github.com/O-ffender/Discord-Mass-Report-Bot)
- [x] [Aperisolve](https://aperisolve.fr)
- [x] [Cyberchef](https://gchq.github.io/CyberChef/)

**Comment by 13-05** [comment]
easy impl! the topics are stretched across files, but mostly found in misc.md.
